"""
Step 5 — Generate Business + Custom + Contact Output Sheets
============================================================
Adapted from: Step5_main_pipelinenupv4.py

Reads city_schema.json (generated by step5_support_generate_city_details.py)
to get field mapping configuration. Produces:

  results/output/final_excel/
    Business_Matched_Records.xlsx
    Additional_Business_Matched_Records.xlsx
    Custom_Matched_Records.xlsx
    Additional_Custom_Matched_Records.xlsx
    Contact_Matched_Records.xlsx
    Additional_Contact_Matched_Records.xlsx

  results/output/final_output/
    {city}_Business_Matched_Records.xlsx   (multi-sheet: Business + Custom + Contact)
    Additional_Matched_Records_Of_{city}.xlsx

REQUIRES: city_schema.json at uploads/{city}/city_schema.json
  Run step5_support_generate_city_details.py ONCE per city to generate it.

NOTE: largest_num_list and earliest_date_list are patched to handle blank/text values.
"""

import os
import json
import math
import logging
import pandas as pd
from datetime import datetime
from pathlib import Path
from sqlalchemy.orm import Session
from openpyxl import load_workbook

from ..db.models import City

logger = logging.getLogger(__name__)


def _patch_fsc(fsc):
    """Apply monkey-patches from Step5_main_pipelinenupv4.py."""

    def _largest_num_list_fixed(city_df, updated_col_name, index):
        max_number_value_list = []
        for data in city_df[updated_col_name[index]]:
            data = str(data).replace(';', ' ')
            if data != '':
                data1 = data.split(' ')
                max_number_value = []
                for i in data1:
                    if i.isnumeric():
                        max_number_value.append(int(i))
                    elif fsc.isfloat(i):
                        max_number_value.append(math.ceil(float(i)))
                    elif not i.isalpha():
                        res = ''.join(filter(lambda x: x.isdigit(), i))
                        if res:
                            max_number_value.append(int(res))
                max_number_value_list.append(max(max_number_value) if max_number_value else '')
            else:
                max_number_value_list.append('')
        return max_number_value_list

    def _earliest_date_list_fixed(city_df, updated_col_name, index):
        from datetime import datetime as _dt
        result = []
        for data in city_df[updated_col_name[index]]:
            data = str(data).replace(';', ' ')
            if data.strip() != '':
                dates = []
                for token in data.split(' '):
                    token = token.strip()
                    if not token:
                        continue
                    try:
                        dates.append(_dt.strptime(token, '%m/%d/%Y'))
                    except (ValueError, TypeError):
                        pass
                result.append(min(dates).strftime('%m/%d/%Y') if dates else '')
            else:
                result.append('')
        return result

    fsc.largest_num_list  = _largest_num_list_fixed
    fsc.earliest_date_list = _earliest_date_list_fixed
    logger.info("Step 5: Patched largest_num_list and earliest_date_list")


def _load_schema(city_dir: Path) -> dict:
    """Load city_schema.json. Raises if not found."""
    schema_path = city_dir / "city_schema.json"
    if not schema_path.exists():
        raise FileNotFoundError(
            f"city_schema.json not found at {schema_path}. "
            "Run step5_support_generate_city_details.py first."
        )
    with open(str(schema_path)) as f:
        return json.load(f)


def _normalize_additional(additional_df, schema):
    """
    Normalize additional_city_match_records column layout
    (from Step5_main_pipelinenupv4.py FIX section).
    """
    CITY_NAME_LIST   = schema.get("CITY_NAME_LIST",   [])
    CITY_ADDRESS_LIST = schema.get("CITY_ADDRESS_LIST", [])
    CITY_PHONE_LIST   = schema.get("CITY_PHONE_LIST",   [])
    COLUMNS_LIST      = schema.get("COLUMNS_LIST",      [])

    _add = additional_df

    def _fill(bludot_col, candidates):
        for src in candidates:
            if src not in _add.columns:
                continue
            if bludot_col not in _add.columns:
                _add[bludot_col] = _add[src]
            else:
                blank = _add[bludot_col].astype(str).str.strip().isin(['', 'nan', 'None'])
                _add.loc[blank, bludot_col] = _add.loc[blank, src]
            return

    _fill('Name_x', list(CITY_NAME_LIST))
    if 'Name_x' in _add.columns and 'Name_x_1' not in _add.columns:
        _add['Name_x_1'] = _add['Name_x']

    _fill('Address1', list(CITY_ADDRESS_LIST))
    if 'Address1' in _add.columns and 'Address1_1' not in _add.columns:
        _add['Address1_1'] = _add['Address1']

    phone_candidates = list(CITY_PHONE_LIST) + [
        c for c in _add.columns
        if 'phone' in c.lower() and 'fax' not in c.lower() and 'mailing' not in c.lower()
    ]
    _fill('PhoneNumber', phone_candidates)
    if 'PhoneNumber' in _add.columns and 'PhoneNumber_1' not in _add.columns:
        _add['PhoneNumber_1'] = _add['PhoneNumber']

    zip_candidates = [
        c for c in _add.columns
        if ('postal' in c.lower() or 'zip' in c.lower()) and 'mailing' not in c.lower()
    ]
    _fill('ZipCode', zip_candidates)
    if 'ZipCode' in _add.columns and 'ZipCode_1' not in _add.columns:
        _add['ZipCode_1'] = _add['ZipCode']

    for col in COLUMNS_LIST:
        if col in ('UUID', 'Valid-Business'):
            continue
        if col not in _add.columns:
            _fill(col, [col, f'{col}_1'])

    return _add


def run_step5(city: City, db: Session, results_dir: str) -> dict:
    """Entry point called by pipeline._step5."""
    try:
        import src.final_sheet_creation as _fsc
        from src.final_sheet_creation import (
            get_Business_Matched_Records,
            get_custom_matched_records,
            get_contact_matched_records,
            format_custom_subsheet,
        )
    except ImportError as e:
        logger.error(f"Step 5: Cannot import src.final_sheet_creation: {e}")
        raise ImportError(
            "src/final_sheet_creation.py not found. "
            "Make sure the src/ folder is present in the backend directory."
        ) from e

    _patch_fsc(_fsc)

    results_path = Path(results_dir)
    city_dir     = results_path.parent  # uploads/{city}/
    city_name    = city.name

    # Load schema
    schema = _load_schema(city_dir)

    # Output dirs
    final_excel  = results_path / "output" / "final_excel"
    final_output = results_path / "output" / "final_output"
    final_excel.mkdir(parents=True, exist_ok=True)
    final_output.mkdir(parents=True, exist_ok=True)

    # Input files
    city_records   = pd.read_excel(str(results_path / "city_data" / "de_duplication_merged.xlsx"), dtype=object)
    bludot_records = pd.read_excel(str(results_path / "bludot_data" / "bludot_concatenated_records.xlsx"), dtype=object)
    raw_sheet      = str(city_dir / "original_record" / city.raw_data_path.split("/")[-1])
    city_records.fillna("", inplace=True)

    final_result = results_path / "output" / "final_result"
    total_match_records = pd.read_excel(
        str(final_result / f"final_matched_records_for_{city_name}.xlsx"), dtype=object)
    additional_city_match_records = pd.read_excel(
        str(final_result / f"additional_city_records_for_{city_name}.xlsx"), dtype=object)

    total_match_records.fillna('', inplace=True)
    additional_city_match_records.fillna('', inplace=True)
    total_match_records           = total_match_records.astype(str)
    additional_city_match_records = additional_city_match_records.astype(str)

    # Normalize additional records column layout
    additional_city_match_records = _normalize_additional(additional_city_match_records, schema)

    # UUID prefix for additional records
    now = datetime.now()
    uuid_for_additional = city_name[:3].upper() + str(now.year) + str(now.month) + str(now.day)

    # Pull mapping from schema
    city_field_mapping    = schema["BUSINESS_MATCHED_CITY_COLUMNS"]
    bludot_field_mapping  = schema["BUSINESS_MATCHED_BLUDOT_COLUMNS"]
    original_record_list  = schema["COLUMNS_LIST"]
    updated_record_list   = schema["COLUMNS_LIST_UPDATED"]
    country_state_mapping = schema.get("COUNTRY_STATE_MAPPING", {})
    city_field_mapping1   = schema["BUSINESS_CUSTOM_MATCHED_CITY_COLUMNS"]
    bludot_field_mapping1 = schema["BUSINESS_CUSTOM_MATCHED_BLUDOT_COLUMNS"]
    NEW_FIELDS            = schema.get("NEW_FIELDS", [])
    city_matched_records2   = schema["CONTACT_MATCHED_CITY_COLUMNS"]
    bludot_matched_records2 = schema["CONTACT_MATCHED_BLUDOT_COLUMNS"]
    BLUDOT_OR_USER = schema.get("BLUDOT_OR_USER", "bludot")

    stats = {"business_matched": 0, "business_additional": 0,
             "custom_matched": 0, "contact_matched": 0}

    # Business records
    custom_matched_records = None
    if city_field_mapping:
        business_matched = get_Business_Matched_Records(
            dataset=total_match_records, city_field_mapping=city_field_mapping,
            bludot_field_mapping=bludot_field_mapping, original_record_list=original_record_list,
            updated_record_list=updated_record_list, country_state_mapping=country_state_mapping,
            method=False, city_records=city_records, uuid_for_additional='',
            source_type=BLUDOT_OR_USER)
        add_business_matched = get_Business_Matched_Records(
            dataset=additional_city_match_records, city_field_mapping=city_field_mapping,
            bludot_field_mapping=bludot_field_mapping, original_record_list=original_record_list,
            updated_record_list=updated_record_list, country_state_mapping=country_state_mapping,
            method=True, city_records=city_records, uuid_for_additional=uuid_for_additional,
            source_type=BLUDOT_OR_USER)
        business_matched.to_excel(str(final_excel / "Business_Matched_Records.xlsx"), index=False)
        add_business_matched.to_excel(str(final_excel / "Additional_Business_Matched_Records.xlsx"), index=False)
        stats["business_matched"]    = len(business_matched)
        stats["business_additional"] = len(add_business_matched)

    # Custom records
    custom_default_value_indexes = []
    add_custom_default_value_indexes = []
    if city_field_mapping1 or NEW_FIELDS:
        for col in NEW_FIELDS:
            if col in additional_city_match_records.columns and f'{col}_1' not in additional_city_match_records.columns:
                additional_city_match_records[f'{col}_1'] = additional_city_match_records[col]

        custom_matched_records, custom_default_value_indexes = get_custom_matched_records(
            dataset=total_match_records, city_field_mapping=city_field_mapping1,
            bludot_field_mapping=bludot_field_mapping1, method=False, uuid_for_additional='',
            new_fields=NEW_FIELDS, raw_sheet=raw_sheet, city_records=city_records,
            filename_output=str(final_excel))
        add_custom_matched_records, add_custom_default_value_indexes = get_custom_matched_records(
            dataset=additional_city_match_records, city_field_mapping=city_field_mapping1,
            bludot_field_mapping=bludot_field_mapping1, method=True,
            uuid_for_additional=uuid_for_additional, raw_sheet=raw_sheet,
            new_fields=NEW_FIELDS, city_records=city_records, filename_output=str(final_excel))
        custom_matched_records.to_excel(str(final_excel / "Custom_Matched_Records.xlsx"), index=False)
        add_custom_matched_records.to_excel(str(final_excel / "Additional_Custom_Matched_Records.xlsx"), index=False)
        stats["custom_matched"] = len(custom_matched_records)

    # Contact records
    if city_matched_records2:
        contact_matched = get_contact_matched_records(
            dataset=total_match_records, city_matched_records=city_matched_records2,
            bludot_matched_records=bludot_matched_records2, uuid_for_additional='', method=False)
        add_contact_matched = get_contact_matched_records(
            dataset=additional_city_match_records, city_matched_records=city_matched_records2,
            bludot_matched_records=bludot_matched_records2, uuid_for_additional=uuid_for_additional,
            method=True)
        contact_matched.to_excel(str(final_excel / "Contact_Matched_Records.xlsx"), index=False)
        add_contact_matched.to_excel(str(final_excel / "Additional_Contact_Matched_Records.xlsx"), index=False)
        stats["contact_matched"] = len(contact_matched)

    # Write combined multi-sheet Excel
    _has_custom = custom_matched_records is not None

    with pd.ExcelWriter(str(final_output / f"{city_name}_Business_Matched_Records.xlsx")) as writer:
        if city_field_mapping:
            business_matched.to_excel(writer, sheet_name="Business_Matched_Records", index=False)
        if _has_custom:
            custom_matched_records.to_excel(writer, sheet_name="Custom_Matched_Records", index=False)
        if city_matched_records2:
            contact_matched.to_excel(writer, sheet_name="Contact_Matched_Records", index=False)

    with pd.ExcelWriter(str(final_output / f"Additional_Matched_Records_Of_{city_name}.xlsx")) as writer:
        if city_field_mapping:
            add_business_matched.to_excel(writer, sheet_name="Additional_Business_Matched_Rec", index=False)
        if _has_custom:
            add_custom_matched_records.to_excel(writer, sheet_name="Additional_Custom_Matched_Rec", index=False)
        if city_matched_records2:
            add_contact_matched.to_excel(writer, sheet_name="Additional_Contact_Matched_Rec", index=False)

    if _has_custom:
        wb1 = load_workbook(str(final_output / f"{city_name}_Business_Matched_Records.xlsx"))
        format_custom_subsheet(wb1, "Custom_Matched_Records", custom_default_value_indexes)
        wb1.save(str(final_output / f"{city_name}_Business_Matched_Records.xlsx"))
        wb2 = load_workbook(str(final_output / f"Additional_Matched_Records_Of_{city_name}.xlsx"))
        format_custom_subsheet(wb2, "Additional_Custom_Matched_Rec", add_custom_default_value_indexes)
        wb2.save(str(final_output / f"Additional_Matched_Records_Of_{city_name}.xlsx"))

    # Update city output path
    city.output_file_path = str(final_output / f"{city_name}_Business_Matched_Records.xlsx")
    db.commit()

    logger.info(f"Step 5 complete: {stats}")
    return stats
